/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Rooms;

import Controller.RoomsController;
import Models.EntitiesManagers.Manager;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22893
 */
public class Roomsviews extends javax.swing.JPanel {

    /**
     * Creates new form Roomsviews
     */
    public Roomsviews() {
        initComponents();
        Manager.connect();
        ROOMLIST_JTABLE.setModel(RoomsController.getAll());//Affiche tout les étudiants dans le tableau
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NUM_CHAMBRE_JLABEL = new javax.swing.JLabel();
        STATUS_JLABEL = new javax.swing.JLabel();
        TYPE_JLABEL = new javax.swing.JLabel();
        CARACTERISTIQUE_JLABEL = new javax.swing.JLabel();
        SITUATION_JLABEL = new javax.swing.JLabel();
        PRIX_JLABEL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        prix_TF = new javax.swing.JTextField();
        situation_CB = new javax.swing.JComboBox<>();
        caractère_CB = new javax.swing.JComboBox<>();
        type_CB = new javax.swing.JComboBox<>();
        status_CB = new javax.swing.JComboBox<>();
        RECHERCHE_JLABEL = new javax.swing.JLabel();
        recherche_TF = new javax.swing.JTextField();
        STOR_BTN = new javax.swing.JButton();
        DELETE_BTN = new javax.swing.JButton();
        UPDATE_BTN = new javax.swing.JButton();
        num_TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ROOMLIST_JTABLE = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setFocusCycleRoot(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 56));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1991, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(382, 764));

        NUM_CHAMBRE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        NUM_CHAMBRE_JLABEL.setText("Room Number :");

        STATUS_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        STATUS_JLABEL.setText("Status :");

        TYPE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TYPE_JLABEL.setText("Room Type :");

        CARACTERISTIQUE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CARACTERISTIQUE_JLABEL.setText("Characteristic :");

        SITUATION_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SITUATION_JLABEL.setText("Situation :");

        PRIX_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PRIX_JLABEL.setText("Price :");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 256));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Rooms/chambre-a-coucher.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("ROOMS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NUM_CHAMBRE_JLABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TYPE_JLABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(STATUS_JLABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CARACTERISTIQUE_JLABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SITUATION_JLABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PRIX_JLABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NUM_CHAMBRE_JLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(STATUS_JLABEL)
                .addGap(47, 47, 47)
                .addComponent(TYPE_JLABEL)
                .addGap(46, 46, 46)
                .addComponent(CARACTERISTIQUE_JLABEL)
                .addGap(51, 51, 51)
                .addComponent(SITUATION_JLABEL)
                .addGap(46, 46, 46)
                .addComponent(PRIX_JLABEL)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, -1, 1206));

        prix_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        prix_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(prix_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 800, 400, 40));

        situation_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        situation_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vue édifice", "vue mer", "vue jardin", "vue rue", "vue montagne" }));
        add(situation_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 710, 400, 40));

        caractère_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        caractère_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Double", "Triple" }));
        add(caractère_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 400, 40));

        type_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        type_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ventilées", "climatisées" }));
        add(type_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 400, 40));

        status_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        status_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dirty", "own" }));
        add(status_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 400, 40));

        RECHERCHE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        RECHERCHE_JLABEL.setForeground(new java.awt.Color(255, 255, 255));
        RECHERCHE_JLABEL.setText(" Research :");
        add(RECHERCHE_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, -1, -1));

        recherche_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        recherche_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recherche_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recherche_TFKeyReleased(evt);
            }
        });
        add(recherche_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 340, 400, 40));

        STOR_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        STOR_BTN.setText("ADD");
        STOR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STOR_BTNActionPerformed(evt);
            }
        });
        add(STOR_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 800, 140, 40));

        DELETE_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DELETE_BTN.setText(" DELETE");
        DELETE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_BTNActionPerformed(evt);
            }
        });
        add(DELETE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 800, 140, 40));

        UPDATE_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UPDATE_BTN.setText("MODIFY");
        UPDATE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_BTNActionPerformed(evt);
            }
        });
        add(UPDATE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 800, 140, 40));

        num_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        num_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(num_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 400, 40));

        ROOMLIST_JTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ROOMLIST_JTABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ROOMLIST_JTABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ROOMLIST_JTABLE);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 860, 1190, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Rooms/fleure2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 63, -1, 1206));
    }// </editor-fold>//GEN-END:initComponents

    private void STOR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STOR_BTNActionPerformed
        // TODO add your handling code here:
         if (RoomsController.store(num_TF.getText(), status_CB.getSelectedItem().toString(), type_CB.getSelectedItem().toString(), caractère_CB.getSelectedItem().toString(), situation_CB.getSelectedItem().toString(), prix_TF.getText())) {
            ROOMLIST_JTABLE.setModel(RoomsController.getAll());
            JOptionPane.showMessageDialog(null, "Insertion réussi");
        }
    }//GEN-LAST:event_STOR_BTNActionPerformed

    private void DELETE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_BTNActionPerformed
        // TODO add your handling code here:
        int myIndex = ROOMLIST_JTABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null, "Aucune line du tableau n'est selectionné");
        } else {
            DefaultTableModel model = (DefaultTableModel) ROOMLIST_JTABLE.getModel();
            if (RoomsController.destroy(Integer.parseInt(model.getValueAt(myIndex, 0).toString()))) {
                ROOMLIST_JTABLE.setModel(RoomsController.getAll());// pour rafraichir la table
            }
        }
    }//GEN-LAST:event_DELETE_BTNActionPerformed

    private void UPDATE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_BTNActionPerformed
        // TODO add your handling code here:
          int myIndex = ROOMLIST_JTABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null,"No table row is selected");
        } else {
            DefaultTableModel model = (DefaultTableModel) ROOMLIST_JTABLE.getModel();
            if (RoomsController.update(Integer.parseInt(model.getValueAt(myIndex, 0).toString()), num_TF.getText(), status_CB.getSelectedItem().toString(), type_CB.getSelectedItem().toString(), caractère_CB.getSelectedItem().toString(), situation_CB.getSelectedItem().toString(), prix_TF.getText())) {
                ROOMLIST_JTABLE.setModel(RoomsController.getAll());
                JOptionPane.showMessageDialog(null, "the modification is carried out successfully");
            }
        }
    }//GEN-LAST:event_UPDATE_BTNActionPerformed

    private void ROOMLIST_JTABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ROOMLIST_JTABLEMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ROOMLIST_JTABLE.getModel();
        
        //pour changer la couleur quand on clique dessus et pour mettre la ligne en exergue
        ROOMLIST_JTABLE.setSelectionForeground(new Color(255, 255, 255, 255));
        ROOMLIST_JTABLE.setSelectionForeground(new Color(232, 57, 95));
        int myIndex = ROOMLIST_JTABLE.getSelectedRow();
        num_TF.setText(model.getValueAt(myIndex, 1).toString());
        status_CB.setSelectedItem(model.getValueAt(myIndex, 2).toString());
        type_CB.setSelectedItem(model.getValueAt(myIndex, 3).toString());
        caractère_CB.setSelectedItem(model.getValueAt(myIndex, 4).toString());
        situation_CB.setSelectedItem(model.getValueAt(myIndex, 5).toString());
        prix_TF.setText(model.getValueAt(myIndex, 6).toString());
    }//GEN-LAST:event_ROOMLIST_JTABLEMouseClicked

    private void recherche_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recherche_TFKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ROOMLIST_JTABLE.getModel();
        ROOMLIST_JTABLE.setModel(RoomsController.search(recherche_TF.getText()));
    }//GEN-LAST:event_recherche_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CARACTERISTIQUE_JLABEL;
    private javax.swing.JButton DELETE_BTN;
    private javax.swing.JLabel NUM_CHAMBRE_JLABEL;
    private javax.swing.JLabel PRIX_JLABEL;
    private javax.swing.JLabel RECHERCHE_JLABEL;
    private javax.swing.JTable ROOMLIST_JTABLE;
    private javax.swing.JLabel SITUATION_JLABEL;
    private javax.swing.JLabel STATUS_JLABEL;
    private javax.swing.JButton STOR_BTN;
    private javax.swing.JLabel TYPE_JLABEL;
    private javax.swing.JButton UPDATE_BTN;
    private javax.swing.JComboBox<String> caractère_CB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField num_TF;
    private javax.swing.JTextField prix_TF;
    private javax.swing.JTextField recherche_TF;
    private javax.swing.JComboBox<String> situation_CB;
    private javax.swing.JComboBox<String> status_CB;
    private javax.swing.JComboBox<String> type_CB;
    // End of variables declaration//GEN-END:variables
}
