/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Articles;

import Controller.ArticlesController;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22893
 */
public class Articlesviews extends javax.swing.JPanel {

    /**
     * Creates new form Articlesviews
     */
    public Articlesviews() {
        initComponents();
         DefaultTableModel model = (DefaultTableModel) ARTICLES_TABLE.getModel();
        ARTICLES_TABLE.setModel(ArticlesController.search(recherche_TF.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NOM_PRODUIT_JLABEL = new javax.swing.JLabel();
        PRIX_JLABEL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_TF = new javax.swing.JTextField();
        prix_TF = new javax.swing.JTextField();
        recherche_TF = new javax.swing.JTextField();
        RECHERCHE_JLABEL = new javax.swing.JLabel();
        AJOUTER_BTN = new javax.swing.JButton();
        MODIFIER_BTN = new javax.swing.JButton();
        SUPRIMER_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ARTICLES_TABLE = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1653, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(382, 764));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 256));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Articles/article.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NOM_PRODUIT_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        NOM_PRODUIT_JLABEL.setText("Name Item :");

        PRIX_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PRIX_JLABEL.setText("Price :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("ITEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PRIX_JLABEL)
                    .addComponent(NOM_PRODUIT_JLABEL))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(NOM_PRODUIT_JLABEL)
                .addGap(71, 71, 71)
                .addComponent(PRIX_JLABEL)
                .addGap(0, 438, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, -1, 964));

        nom_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nom_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_TFActionPerformed(evt);
            }
        });
        add(nom_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 410, 40));

        prix_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        prix_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(prix_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 410, 40));

        recherche_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        recherche_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recherche_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherche_TFActionPerformed(evt);
            }
        });
        recherche_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recherche_TFKeyReleased(evt);
            }
        });
        add(recherche_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 430, 410, 40));

        RECHERCHE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        RECHERCHE_JLABEL.setForeground(new java.awt.Color(255, 255, 255));
        RECHERCHE_JLABEL.setText(" Research :");
        add(RECHERCHE_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 220, 60));

        AJOUTER_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AJOUTER_BTN.setText("ADD");
        AJOUTER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AJOUTER_BTNActionPerformed(evt);
            }
        });
        add(AJOUTER_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 711, 130, 40));

        MODIFIER_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MODIFIER_BTN.setText("MODIFY");
        MODIFIER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFIER_BTNActionPerformed(evt);
            }
        });
        add(MODIFIER_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 711, 130, 40));

        SUPRIMER_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SUPRIMER_BTN.setText("DELETE");
        SUPRIMER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPRIMER_BTNActionPerformed(evt);
            }
        });
        add(SUPRIMER_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 711, 130, 40));

        ARTICLES_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ARTICLES_TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ARTICLES_TABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ARTICLES_TABLE);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 770, 1170, 230));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Articles/fleure2.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 1260, 960));
    }// </editor-fold>//GEN-END:initComponents

    private void recherche_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherche_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recherche_TFActionPerformed

    private void AJOUTER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AJOUTER_BTNActionPerformed
        // TODO add your handling code here:
          if (ArticlesController.store(nom_TF.getText(), prix_TF.getText())) {
            ARTICLES_TABLE.setModel(ArticlesController.getAll());
            JOptionPane.showMessageDialog(null, "Insertion réussi");
        }
          
    }//GEN-LAST:event_AJOUTER_BTNActionPerformed

    private void SUPRIMER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPRIMER_BTNActionPerformed
        // TODO add your handling code here:
         int myIndex = ARTICLES_TABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null, "Aucune line du tableau n'est selectionné");
        } else {
            DefaultTableModel model = (DefaultTableModel) ARTICLES_TABLE.getModel();
            if (ArticlesController.destroy(Integer.parseInt(model.getValueAt(myIndex, 0).toString()))) {
                ARTICLES_TABLE.setModel(ArticlesController.getAll());// pour rafraichir la table
            }
        }
    }//GEN-LAST:event_SUPRIMER_BTNActionPerformed

    private void MODIFIER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFIER_BTNActionPerformed
        // TODO add your handling code here:
          int myIndex = ARTICLES_TABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null,"No table row is selected");
        } else {
            DefaultTableModel model = (DefaultTableModel) ARTICLES_TABLE.getModel();
            if (ArticlesController.update(Integer.parseInt(model.getValueAt(myIndex, 0).toString()), nom_TF.getText(), prix_TF.getText())) {
                ARTICLES_TABLE.setModel(ArticlesController.getAll());
                JOptionPane.showMessageDialog(null, "the modification is carried out successfully");
            }
        }
    }//GEN-LAST:event_MODIFIER_BTNActionPerformed

    private void ARTICLES_TABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ARTICLES_TABLEMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) ARTICLES_TABLE.getModel();
        
        //pour changer la couleur quand on clique dessus et pour mettre la ligne en exergue
        ARTICLES_TABLE.setSelectionForeground(new Color(255, 255, 255, 255));
        ARTICLES_TABLE.setSelectionForeground(new Color(232, 57, 95));
        int myIndex = ARTICLES_TABLE.getSelectedRow();
        nom_TF.setText(model.getValueAt(myIndex, 1).toString());
        prix_TF.setText(model.getValueAt(myIndex, 2).toString());
    }//GEN-LAST:event_ARTICLES_TABLEMouseClicked

    private void recherche_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recherche_TFKeyReleased
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) ARTICLES_TABLE.getModel();
        ARTICLES_TABLE.setModel(ArticlesController.search(recherche_TF.getText()));
    }//GEN-LAST:event_recherche_TFKeyReleased

    private void nom_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_TFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AJOUTER_BTN;
    private javax.swing.JTable ARTICLES_TABLE;
    private javax.swing.JButton MODIFIER_BTN;
    private javax.swing.JLabel NOM_PRODUIT_JLABEL;
    private javax.swing.JLabel PRIX_JLABEL;
    private javax.swing.JLabel RECHERCHE_JLABEL;
    private javax.swing.JButton SUPRIMER_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nom_TF;
    private javax.swing.JTextField prix_TF;
    private javax.swing.JTextField recherche_TF;
    // End of variables declaration//GEN-END:variables
}
