/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Controller.CustomersController;
import Models.EntitiesManagers.Manager;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22893
 */
public class Customersviews extends javax.swing.JPanel {

    /**
     * Creates new form Customersviews
     */
    public Customersviews() {
        initComponents();
        Manager.connect();
        CUSTOMERS_LIST_JTABLE.setModel(CustomersController.getAll());
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        FIRST_NAME_JLABEL = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        CONTRY_JLABEL = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        CARTE_JLABEL = new javax.swing.JLabel();
        LAST_NAME_JLABEL = new javax.swing.JLabel();
        PHONE_JLABEL = new javax.swing.JLabel();
        TYPE_JLABEL = new javax.swing.JLabel();
        last_name_TF = new javax.swing.JTextField();
        firt_name_TF = new javax.swing.JTextField();
        phone_TF = new javax.swing.JTextField();
        pays_CB = new javax.swing.JComboBox<>();
        type_client_CB = new javax.swing.JComboBox<>();
        carte_CB = new javax.swing.JComboBox<>();
        recherche_TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CUSTOMERS_LIST_JTABLE = new javax.swing.JTable();
        AJOUTER_JB = new javax.swing.JButton();
        SUPRIMER_JB = new javax.swing.JButton();
        MODIFIER_JB = new javax.swing.JButton();
        RECHERCHE_JLABEL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1747, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 1030));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(420, 180));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 400, 250));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(420, 70));

        FIRST_NAME_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        FIRST_NAME_JLABEL.setText("Prénom :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(FIRST_NAME_JLABEL)
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FIRST_NAME_JLABEL)
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(420, 70));

        CONTRY_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CONTRY_JLABEL.setText("Citoyen :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(CONTRY_JLABEL)
                .addGap(47, 47, 47))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CONTRY_JLABEL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(420, 70));

        CARTE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CARTE_JLABEL.setText("Carte Fidélitée : ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(CARTE_JLABEL)
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CARTE_JLABEL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        LAST_NAME_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LAST_NAME_JLABEL.setText("    Nom :");
        jPanel2.add(LAST_NAME_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        PHONE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PHONE_JLABEL.setText("Num de Téléphone :");
        jPanel2.add(PHONE_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        TYPE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TYPE_JLABEL.setText("Type Client :");
        jPanel2.add(TYPE_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 230, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 1200));

        last_name_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        last_name_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_TFActionPerformed(evt);
            }
        });
        add(last_name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 470, 40));

        firt_name_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(firt_name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 470, 40));

        phone_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(phone_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 470, 40));

        pays_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pays_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUI", "NON" }));
        add(pays_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 470, 40));

        type_client_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        type_client_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AUTRES", "CLIENTS PRIVÉS", "CLIENTS AFFAIRES", "CLIENTS GROUPES", "VIP" }));
        add(type_client_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 470, 40));

        carte_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        carte_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUI", "NON" }));
        add(carte_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 470, 40));

        recherche_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherche_TFActionPerformed(evt);
            }
        });
        recherche_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recherche_TFKeyReleased(evt);
            }
        });
        add(recherche_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 220, 470, 40));

        CUSTOMERS_LIST_JTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CUSTOMERS_LIST_JTABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CUSTOMERS_LIST_JTABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CUSTOMERS_LIST_JTABLE);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, 1510, 140));

        AJOUTER_JB.setText("AJOUTER");
        AJOUTER_JB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AJOUTER_JBActionPerformed(evt);
            }
        });
        add(AJOUTER_JB, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 700, 120, 40));

        SUPRIMER_JB.setText("SUPRIMER");
        SUPRIMER_JB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPRIMER_JBActionPerformed(evt);
            }
        });
        add(SUPRIMER_JB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 700, 120, 40));

        MODIFIER_JB.setText("MODIFIER");
        MODIFIER_JB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFIER_JBActionPerformed(evt);
            }
        });
        add(MODIFIER_JB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 710, 120, 40));

        RECHERCHE_JLABEL.setBackground(new java.awt.Color(255, 255, 255));
        RECHERCHE_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        RECHERCHE_JLABEL.setForeground(new java.awt.Color(255, 255, 255));
        RECHERCHE_JLABEL.setText("  Recherche :");
        add(RECHERCHE_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/fleure2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1570, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void recherche_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherche_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recherche_TFActionPerformed

    private void last_name_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_TFActionPerformed

    private void AJOUTER_JBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AJOUTER_JBActionPerformed
        // TODO add your handling code here:
        if (CustomersController.store(last_name_TF.getText(), firt_name_TF.getText(), phone_TF.getText(), pays_CB.getSelectedItem().toString(), type_client_CB.getSelectedItem().toString(), carte_CB.getSelectedItem().toString())) {
            CUSTOMERS_LIST_JTABLE.setModel(CustomersController.getAll());
            JOptionPane.showMessageDialog(null, " Insertion réussi ");
        }
    }//GEN-LAST:event_AJOUTER_JBActionPerformed

    private void SUPRIMER_JBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPRIMER_JBActionPerformed
        // TODO add your handling code here: int myIndex = CUSTOMERS_LIST_JTABLE.getSelectedRow();
        int myIndex = CUSTOMERS_LIST_JTABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null, " Aucune line du tableau n'est selectionné ");
        } else {
            DefaultTableModel model = (DefaultTableModel) CUSTOMERS_LIST_JTABLE.getModel();
            if (CustomersController.destroy(Integer.parseInt(model.getValueAt(myIndex, 0).toString()))) {
                CUSTOMERS_LIST_JTABLE.setModel(CustomersController.getAll());// pour rafraichir la table
            }
        }
    }//GEN-LAST:event_SUPRIMER_JBActionPerformed

    private void MODIFIER_JBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFIER_JBActionPerformed
        // TODO add your handling code here:
           int myIndex = CUSTOMERS_LIST_JTABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null," No table row is selected ");
        } else {
            DefaultTableModel model = (DefaultTableModel) CUSTOMERS_LIST_JTABLE.getModel();
            if (CustomersController.update(Integer.parseInt(model.getValueAt(myIndex, 0).toString()), last_name_TF.getText(), firt_name_TF.getText(), phone_TF.getText(), pays_CB.getSelectedItem().toString(), type_client_CB.getSelectedItem().toString(), carte_CB.getSelectedItem().toString())) {
                CUSTOMERS_LIST_JTABLE.setModel(CustomersController.getAll());
                JOptionPane.showMessageDialog(null, "the modification is carried out successfully");
            }
        }
    }//GEN-LAST:event_MODIFIER_JBActionPerformed

    private void CUSTOMERS_LIST_JTABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUSTOMERS_LIST_JTABLEMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) CUSTOMERS_LIST_JTABLE.getModel();
        
        //pour changer la couleur quand on clique dessus et pour mettre la ligne en exergue
        CUSTOMERS_LIST_JTABLE.setSelectionForeground(new Color(255, 255, 255, 255));
        CUSTOMERS_LIST_JTABLE.setSelectionForeground(new Color(232, 57, 95));
        int myIndex = CUSTOMERS_LIST_JTABLE.getSelectedRow();
        last_name_TF.setText(model.getValueAt(myIndex, 2).toString());
        firt_name_TF.setText(model.getValueAt(myIndex, 3).toString());
        phone_TF.setText(model.getValueAt(myIndex, 4).toString());
        pays_CB.setSelectedItem(model.getValueAt(myIndex, 5).toString());
        type_client_CB.setSelectedItem(model.getValueAt(myIndex, 6).toString());
        carte_CB.setSelectedItem(model.getValueAt(myIndex, 7).toString());
    }//GEN-LAST:event_CUSTOMERS_LIST_JTABLEMouseClicked

    private void recherche_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recherche_TFKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) CUSTOMERS_LIST_JTABLE.getModel();
        CUSTOMERS_LIST_JTABLE.setModel(CustomersController.search(recherche_TF.getText()));
    }//GEN-LAST:event_recherche_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AJOUTER_JB;
    private javax.swing.JLabel CARTE_JLABEL;
    private javax.swing.JLabel CONTRY_JLABEL;
    private javax.swing.JTable CUSTOMERS_LIST_JTABLE;
    private javax.swing.JLabel FIRST_NAME_JLABEL;
    private javax.swing.JLabel LAST_NAME_JLABEL;
    private javax.swing.JButton MODIFIER_JB;
    private javax.swing.JLabel PHONE_JLABEL;
    private javax.swing.JLabel RECHERCHE_JLABEL;
    private javax.swing.JButton SUPRIMER_JB;
    private javax.swing.JLabel TYPE_JLABEL;
    private javax.swing.JComboBox<String> carte_CB;
    private javax.swing.JTextField firt_name_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_name_TF;
    private javax.swing.JComboBox<String> pays_CB;
    private javax.swing.JTextField phone_TF;
    private javax.swing.JTextField recherche_TF;
    private javax.swing.JComboBox<String> type_client_CB;
    // End of variables declaration//GEN-END:variables
}
