/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Users;

import Controller.UsersController;
import Models.EntitiesManagers.Manager;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22893
 */
public class Usersviews extends javax.swing.JPanel {

    /**
     * Creates new form Usersviews
     */
    public Usersviews() {
        initComponents();
        Manager.connect();
        //Affiche tout les étudiants dans le tableau
        USERLIST_JTABLE.setModel(UsersController.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        USERNAME_JLABEL = new javax.swing.JLabel();
        PASSWORD_JLABEL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name_TF = new javax.swing.JTextField();
        Recherche_TF = new javax.swing.JTextField();
        RECHERCHE_jLABEL = new javax.swing.JLabel();
        UPDATE_BTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DELETE_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        USERLIST_JTABLE = new javax.swing.JTable();
        Password_TF = new javax.swing.JPasswordField();
        password_CB = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 56));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1935, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1935, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(382, 1200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 312, 230, 10));

        USERNAME_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        USERNAME_JLABEL.setText("Users Name :");
        jPanel2.add(USERNAME_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 358, -1, -1));

        PASSWORD_JLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PASSWORD_JLABEL.setText("Password :");
        jPanel2.add(PASSWORD_JLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 480, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 256));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Users/utilisateur.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("USERS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, -1, -1));

        Name_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Name_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 430, 40));

        Recherche_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Recherche_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Recherche_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recherche_TFActionPerformed(evt);
            }
        });
        Recherche_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Recherche_TFKeyReleased(evt);
            }
        });
        add(Recherche_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 420, 430, 40));

        RECHERCHE_jLABEL.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        RECHERCHE_jLABEL.setForeground(new java.awt.Color(255, 255, 255));
        RECHERCHE_jLABEL.setText("Research :");
        add(RECHERCHE_jLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 220, 50));

        UPDATE_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UPDATE_BTN.setText("MODIFY");
        UPDATE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_BTNActionPerformed(evt);
            }
        });
        add(UPDATE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 750, 140, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, 140, 40));

        DELETE_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DELETE_BTN.setText("DELETE");
        DELETE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_BTNActionPerformed(evt);
            }
        });
        add(DELETE_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 750, 140, 40));

        USERLIST_JTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        USERLIST_JTABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USERLIST_JTABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(USERLIST_JTABLE);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 860, 1220, 150));

        Password_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Password_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TFActionPerformed(evt);
            }
        });
        add(Password_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 430, 40));

        password_CB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password_CB.setForeground(new java.awt.Color(153, 153, 153));
        password_CB.setText("Show password");
        password_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_CBActionPerformed(evt);
            }
        });
        add(password_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 540, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Users/fleure2.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 63, 1541, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Recherche_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recherche_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recherche_TFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (UsersController.store(Name_TF.getText(), Password_TF.getText())) {
            USERLIST_JTABLE.setModel(UsersController.getAll());
            JOptionPane.showMessageDialog(null, "Insertion réussi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DELETE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_BTNActionPerformed
        // TODO add your handling code here:
        int myIndex = USERLIST_JTABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null, "Aucune line du tableau n'est selectionné");
        } else {
            DefaultTableModel model = (DefaultTableModel) USERLIST_JTABLE.getModel();
            if (UsersController.destroy(Integer.parseInt(model.getValueAt(myIndex, 0).toString()))) {
                USERLIST_JTABLE.setModel(UsersController.getAll());// pour rafraichir la table
            }
        }
    }//GEN-LAST:event_DELETE_BTNActionPerformed

    private void UPDATE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_BTNActionPerformed
        // TODO add your handling code here:
        //Controller.LoginController.update();
        
        int myIndex = USERLIST_JTABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null,"No table row is selected");
        } else {
            DefaultTableModel model = (DefaultTableModel) USERLIST_JTABLE.getModel();
            if (UsersController.update(Integer.parseInt(model.getValueAt(myIndex, 0).toString()), Name_TF.getText(), jLabel3.getText())) {
                USERLIST_JTABLE.setModel(UsersController.getAll());
                JOptionPane.showMessageDialog(null, "the modification is carried out successfully");
            }
        }
    }//GEN-LAST:event_UPDATE_BTNActionPerformed

    private void USERLIST_JTABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERLIST_JTABLEMouseClicked
        // TODO add your handling code here:
        // declaration du modele actuel utilisé
        DefaultTableModel model = (DefaultTableModel) USERLIST_JTABLE.getModel();
        //pour changer la couleur quand on clique dessus et pour mettre la ligne en exergue
        USERLIST_JTABLE.setSelectionForeground(new Color(255, 255, 255, 255));
        USERLIST_JTABLE.setSelectionForeground(new Color(232, 57, 95));
        int myIndex = USERLIST_JTABLE.getSelectedRow();
        Name_TF.setText(model.getValueAt(myIndex, 1).toString());
        jLabel3.setText("");
    }//GEN-LAST:event_USERLIST_JTABLEMouseClicked

    private void Recherche_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Recherche_TFKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) USERLIST_JTABLE.getModel();
        USERLIST_JTABLE.setModel(UsersController.search(Recherche_TF.getText()));
    }//GEN-LAST:event_Recherche_TFKeyReleased

    private void Password_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TFActionPerformed

    private void password_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_CBActionPerformed
        // TODO add your handling code here:
        if (password_CB.isSelected()){
            Password_TF.setEchoChar((char)0);
        }else{
            Password_TF.setEchoChar('*');
        }
    }//GEN-LAST:event_password_CBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE_BTN;
    private javax.swing.JTextField Name_TF;
    private javax.swing.JLabel PASSWORD_JLABEL;
    private javax.swing.JPasswordField Password_TF;
    private javax.swing.JLabel RECHERCHE_jLABEL;
    private javax.swing.JTextField Recherche_TF;
    private javax.swing.JButton UPDATE_BTN;
    private javax.swing.JTable USERLIST_JTABLE;
    private javax.swing.JLabel USERNAME_JLABEL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox password_CB;
    // End of variables declaration//GEN-END:variables
}
