/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Purshases;

import Controller.PurshasesController;
import Controller.ReservationsController;
import Models.EntitiesManagers.Manager;
import static Models.EntitiesManagers.Manager.connection;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22893
 */
public class Purshasesviews extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Purshasesviews() {
        initComponents();
        Manager.connect();
        ACHATS_TABLE.setModel(PurshasesController.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paye_CB = new javax.swing.JComboBox<>();
        quantité_TF = new javax.swing.JTextField();
        AJOUTER_BTN = new javax.swing.JButton();
        SUPRIMER_BTN = new javax.swing.JButton();
        MODIFIER_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ACHATS_TABLE = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        recherche_TF = new javax.swing.JTextField();
        article_CB = new javax.swing.JComboBox<>();
        client_CB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1653, 1023));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 56));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("PURSHASES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1991, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(382, 764));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 256));
        jPanel3.setRequestFocusEnabled(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Purshases/achat-en-ligne.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Id Article :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Id Customer :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Quantity :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Payment :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, -1, 1200));

        paye_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        paye_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUI", "NON" }));
        add(paye_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 680, 310, 40));

        quantité_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quantité_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(quantité_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 310, 40));

        AJOUTER_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AJOUTER_BTN.setText("ADD");
        AJOUTER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AJOUTER_BTNActionPerformed(evt);
            }
        });
        add(AJOUTER_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 690, 130, 40));

        SUPRIMER_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SUPRIMER_BTN.setText("DELETE");
        SUPRIMER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPRIMER_BTNActionPerformed(evt);
            }
        });
        add(SUPRIMER_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 690, 130, 40));

        MODIFIER_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MODIFIER_BTN.setText("MODIFY");
        MODIFIER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFIER_BTNActionPerformed(evt);
            }
        });
        add(MODIFIER_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 690, 130, 40));

        ACHATS_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ACHATS_TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACHATS_TABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ACHATS_TABLE);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 770, 1240, 320));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Research :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 240, 30));

        recherche_TF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        recherche_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recherche_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recherche_TFKeyReleased(evt);
            }
        });
        add(recherche_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, 310, 40));

        article_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        article_CB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                article_CBMouseClicked(evt);
            }
        });
        add(article_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 310, 40));

        client_CB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        client_CB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                client_CBMouseClicked(evt);
            }
        });
        client_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_CBActionPerformed(evt);
            }
        });
        add(client_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 310, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Purshases/fleure2.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 63, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AJOUTER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AJOUTER_BTNActionPerformed
        // TODO add your handling code here:
          if (PurshasesController.store(article_CB.getSelectedItem().toString(), client_CB.getSelectedItem().toString(), quantité_TF.getText(), paye_CB.getSelectedItem().toString())) {
            ACHATS_TABLE.setModel(PurshasesController.getAll());
            JOptionPane.showMessageDialog(null, "Insertion réussi");
        }
    }//GEN-LAST:event_AJOUTER_BTNActionPerformed

    private void SUPRIMER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPRIMER_BTNActionPerformed
        // TODO add your handling code here:
          int myIndex = ACHATS_TABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null, " Aucune line du tableau n'est selectionné ");
        } else {
                    DefaultTableModel model = (DefaultTableModel) ACHATS_TABLE.getModel();
            if (PurshasesController.destroy(Integer.parseInt(model.getValueAt(myIndex, 0).toString()))) {
                ACHATS_TABLE.setModel(PurshasesController.getAll());// pour rafraichir la table
            }
        }
    }//GEN-LAST:event_SUPRIMER_BTNActionPerformed

    private void MODIFIER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFIER_BTNActionPerformed
        // TODO add your handling code here:
           int myIndex = ACHATS_TABLE.getSelectedRow();
        if (myIndex == -1) {
            JOptionPane.showMessageDialog(null," No table row is selected ");
        } else {
            DefaultTableModel model = (DefaultTableModel) ACHATS_TABLE.getModel();
            if (PurshasesController.update(Integer.parseInt(model.getValueAt(myIndex, 0).toString()), article_CB.getSelectedItem().toString(), client_CB.getSelectedItem().toString(), quantité_TF.getText(), paye_CB.getSelectedItem().toString())) {
                ACHATS_TABLE.setModel(PurshasesController.getAll());
                JOptionPane.showMessageDialog(null, "the modification is carried out successfully");
            }
        }
    }//GEN-LAST:event_MODIFIER_BTNActionPerformed

    private void recherche_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recherche_TFKeyReleased
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) ACHATS_TABLE.getModel();
         ACHATS_TABLE.setModel(PurshasesController.search(recherche_TF.getText()));
    }//GEN-LAST:event_recherche_TFKeyReleased

    private void ACHATS_TABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACHATS_TABLEMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) ACHATS_TABLE.getModel();
        
        //pour changer la couleur quand on clique dessus et pour mettre la ligne en exergue
        ACHATS_TABLE.setSelectionForeground(new Color(255, 255, 255, 255));
        ACHATS_TABLE.setSelectionForeground(new Color(232, 57, 95));
        int myIndex = ACHATS_TABLE.getSelectedRow();
        article_CB.setSelectedItem(model.getValueAt(myIndex, 1).toString());
        client_CB.setSelectedItem(model.getValueAt(myIndex, 2).toString());
        quantité_TF.setText(model.getValueAt(myIndex, 3).toString());
        paye_CB.setSelectedItem(model.getValueAt(myIndex, 4).toString());
        
    }//GEN-LAST:event_ACHATS_TABLEMouseClicked

    private void client_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_CBActionPerformed

    private void article_CBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_article_CBMouseClicked
        // TODO add your handling code here:
        try {
            Manager.connect();
            String query = "SELECT * FROM articles";
            ResultSet resultSet = connection.createStatement().executeQuery(query);
            article_CB.removeAllItems();
            while (resultSet.next()) {
                article_CB.addItem(resultSet.getString("id"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_article_CBMouseClicked

    private void client_CBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_client_CBMouseClicked
        // TODO add your handling code here:
        try {
            Manager.connect();
            String query = "SELECT * FROM customers";
            ResultSet resultSet = connection.createStatement().executeQuery(query);
            client_CB.removeAllItems();
            while (resultSet.next()) {
                client_CB.addItem(resultSet.getString("id"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_client_CBMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ACHATS_TABLE;
    private javax.swing.JButton AJOUTER_BTN;
    private javax.swing.JButton MODIFIER_BTN;
    private javax.swing.JButton SUPRIMER_BTN;
    private javax.swing.JComboBox<String> article_CB;
    private javax.swing.JComboBox<String> client_CB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> paye_CB;
    private javax.swing.JTextField quantité_TF;
    private javax.swing.JTextField recherche_TF;
    // End of variables declaration//GEN-END:variables
}
